### ISSUE TITLE
Please update node version to v20

### ISSUE THREAD

**Issue by acooler15** [ilharp/sign-android-release#19]
[GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by chika0801** [comment]
Looking forward to your revisions, thank you.

**Comment by yong2khoo-lm** [comment]
@ilharp to verify, the latest build now, shows failed status right?
![image](https://github.com/ilharp/sign-android-release/assets/51041738/3d502e4a-6af2-4920-b6d5-c22bda4f92cc)

**Comment by ilharp** [comment]
> @ilharp to verify, the latest build now, shows failed status right?

Yes. The [action job log](https://github.com/ilharp/sign-android-release/actions/runs/9492593141/job/26159959341) shows that it's due to a network timeout.

![image](https://github.com/ilharp/sign-android-release/assets/20179549/55d66325-550f-4ef9-b4ea-85df591f0ebd)

I've triggered a rerun of this job and it now passes successfully. If you have further questions, feel free to create a new issue.

**Comment by yong2khoo-lm** [comment]
@ilharp  Thanks for your clarification. 
Honestly, i am curious on how to use the one with node20. (allow me to stay on this issue first)

> - uses: ilharp/sign-android-release@v1 # Or use @nightly

From understanding, this doesn't seem to work. Maybe i overlook some configuration. Appreciate if you can shed some light on this.
